### ISSUE TITLE
New Deployment Descriptor section under concepts 

### ISSUE THREAD

**Issue by giobart** [oakestra/documentation#14]
# Proposal

We might add a deployment descriptor section under concepts highlighting the different keywords of the document and, therefore, the different functionalities.
E.g. unikernels, one-shot service etc.

**Comment by nitindermohan** [comment]
Documentation gas been added with PR https://github.com/oakestra/documentation/commit/c5b4131a4edf44fe4cd3174759eecc374e0377f8
