### ISSUE TITLE
Get started deploying Unikernel

### ISSUE THREAD

**Issue by giobart** [oakestra/documentation#2]
Short markdown with an example deployment descriptor about how to deploy Unikernel applications in Oakestra.

_Originally posted by @giobart in https://github.com/oakestra/oakestra/issues/163#issuecomment-1458146118_

**Comment by nitindermohan** [comment]
Documentation has been added with PR https://github.com/oakestra/documentation/commit/c5b4131a4edf44fe4cd3174759eecc374e0377f8
